root = "."
tmp_dir = "tmp"

[build]
  cmd = "go build -o ./tmp/edgectl ./cmd/miragectl"
  bin = "./tmp/edgectl"
  full_bin = ""
  include_ext = ["go"]
  exclude_dir = ["tmp", "edgeui", "vendor", ".git", ".github"]
  delay = 200
  log = "air-build.log"
  stop_on_error = true

[color]
  main = "yellow"
  watcher = "cyan"
  build = "green"
  runner = "magenta"

[log]
  time = true
